@extends('layouts.app')
@section('title', 'My new website')
@section('zone1', 'up')
@section('zone2', 'middle')
@section('zone3' ,'down')
@section('content-up','Sometimes you may need to pass additional data to a component. For this reason, you can pass an array of data as the second argument to the @component directive. All of the data will be made available to the component template as variables: Now, we can inject content into the named slot using the @slot directive. Any content not within a @slot directive will be passed to the component in the $slot variable')
@section('content-mid','In pellentesque tortor vel malesuada vestibulum. Fusce venenatis elit et nunc dignissim facilisis. Sed porttitor consectetur dignissim. Praesent facilisis tempus ligula ac venenatis. Donec vulputate nisi ac sapien dignissim, et egestas leo sollicitudin. Suspendisse et tortor ac libero sollicitudin condimentum sed sed ipsum. Suspendisse ac placerat mauris. Nulla et commodo mi, vitae eleifend nunc. Nullam nec nulla quis nisl lacinia condimentum quis a urna. Proin risus libero, condimentum quis interdum nec, lacinia in urna.')
@section('content-down','Etiam justo diam, faucibus id massa nec, fermentum ornare arcu. Pellentesque hendrerit augue efficitur urna faucibus, sit amet volutpat augue vulputate. Aliquam pretium urna quis sagittis lacinia. Nam quis varius ligula. Nunc congue dapibus felis. Vivamus id mollis libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi odio elit, placerat ut consectetur vel, tincidunt sed lorem. Aenean lacus enim, auctor eu feugiat id, convallis vel urna. Aliquam erat volutpat. Nulla id sapien eget diam molestie pretium ut sed quam. Praesent porta ex pharetra porttitor dapibus.')
@section('line1', 'This is the fsirt line!')
@section('line2', 'This is the line below the first one!')
@section('line3', 'This is the 4th line.')
@section('line4', "You think that was a mistake but didn't notice the one on the first line.")
@section('line5', 'Right?')